name: Generate changelog
on:
  release:
    types: [created, edited]

jobs:
  auto-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: BobAnkh/auto-generate-changelog@v1.3.1
        with:
<<<<<<< HEAD
<<<<<<< HEAD
          REPO_NAME: "Anothays/todo-api-node"
          ACCESS_TOKEN: ${{secrets.GITHUBACTIONS}}
          PATH: "CHANGELOG.md"
          COMMIT_MESSAGE: "docs(CHANGELOG): update release notes"
          TYPE: "feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements,test:Test"
=======
          REPO_NAME: "<Anothays>/<todo-api-node>"
=======
          REPO_NAME: "Anothays/todo-api-node"
>>>>>>> 7ed349c (Automated changelog (#31))
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PATH: "CHANGELOG.md"
          COMMIT_MESSAGE: "docs(CHANGELOG): update release notes"
          TYPE: "feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements,test:Test"
>>>>>>> c3da1f1 (ci: Automated changelog (#29))
