name: CI (lint, test, quality-gate, security-scan)

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Lint
        run: npx eslint .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Test
        run: npm run test -- --coverage
        env:
          SECRET_KEY: TESTING_SECRET_KEY
          API_KEY: TestingApiKey
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.node-version }}
          path: coverage/
          retention-days: 5
      - name: Send coverage to SonarCloud
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Build Docker image
        run: docker build -t todo-app:latest .
      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.34.1
        with:
          image-ref: "todo-app:latest"
          format: "table"
          exit-code: 1
          ignore-unfixed: true
          severity: "CRITICAL"
